// Code generated by mockery v2.42.3. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// Authenticator is an autogenerated mock type for the Authenticator type
type Authenticator struct {
	mock.Mock
}

type Authenticator_Expecter struct {
	mock *mock.Mock
}

func (_m *Authenticator) EXPECT() *Authenticator_Expecter {
	return &Authenticator_Expecter{mock: &_m.Mock}
}

// Authenticate provides a mock function with given fields: _a0
func (_m *Authenticator) Authenticate(_a0 http.Handler) http.Handler {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 http.Handler
	if rf, ok := ret.Get(0).(func(http.Handler) http.Handler); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.Handler)
		}
	}

	return r0
}

// Authenticator_Authenticate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authenticate'
type Authenticator_Authenticate_Call struct {
	*mock.Call
}

// Authenticate is a helper method to define mock.On call
//   - _a0 http.Handler
func (_e *Authenticator_Expecter) Authenticate(_a0 interface{}) *Authenticator_Authenticate_Call {
	return &Authenticator_Authenticate_Call{Call: _e.mock.On("Authenticate", _a0)}
}

func (_c *Authenticator_Authenticate_Call) Run(run func(_a0 http.Handler)) *Authenticator_Authenticate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.Handler))
	})
	return _c
}

func (_c *Authenticator_Authenticate_Call) Return(_a0 http.Handler) *Authenticator_Authenticate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Authenticator_Authenticate_Call) RunAndReturn(run func(http.Handler) http.Handler) *Authenticator_Authenticate_Call {
	_c.Call.Return(run)
	return _c
}

// NewAuthenticator creates a new instance of Authenticator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthenticator(t interface {
	mock.TestingT
	Cleanup(func())
}) *Authenticator {
	mock := &Authenticator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
