// Code generated by mockery v2.42.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// DDNS is an autogenerated mock type for the DDNS type
type DDNS struct {
	mock.Mock
}

type DDNS_Expecter struct {
	mock *mock.Mock
}

func (_m *DDNS) EXPECT() *DDNS_Expecter {
	return &DDNS_Expecter{mock: &_m.Mock}
}

// NewDDNS creates a new instance of DDNS. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDDNS(t interface {
	mock.TestingT
	Cleanup(func())
}) *DDNS {
	mock := &DDNS{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
